version: '3'

services:
  db:
    image: postgres:14-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    container_name: schedule_manager
    volumes:
        - ./postgres:/var/lib/postgresql/data